module.exports = [
    { name: 'Australia', slug: 'au', currency: 'AUD', symbol: '$', extraPayments: ['PayID', 'BPAY'] },
    { name: 'Austria', slug: 'at', currency: 'EUR', symbol: '€', extraPayments: ['EPS Transfer', 'SEPA Instant'] },
    { name: 'Bahrain', slug: 'bh', currency: 'BHD', symbol: '.د.ب', extraPayments: ['BenefitPay'] },
    { name: 'Bangladesh', slug: 'bd', currency: 'BDT', symbol: '৳', extraPayments: ['bKash', 'Nagad', 'Rocket'] },
    { name: 'Belgium', slug: 'be', currency: 'EUR', symbol: '€', extraPayments: ['Bancontact', 'Payconiq'] },
    { name: 'Brazil', slug: 'br', currency: 'BRL', symbol: 'R$', extraPayments: ['Pix', 'Boleto Bancário'] },
    { name: 'Canada', slug: 'ca', currency: 'CAD', symbol: '$', extraPayments: ['Interac e-Transfer'] },
    { name: 'China', slug: 'cn', currency: 'CNY', symbol: '¥', extraPayments: ['Alipay', 'WeChat Pay'] },
    { name: 'Colombia', slug: 'co', currency: 'COP', symbol: '$', extraPayments: ['Nequi', 'Daviplata', 'PSE'] },
    { name: 'Egypt', slug: 'eg', currency: 'EGP', symbol: 'E£', extraPayments: ['InstaPay', 'Vodafone Cash'] },
    { name: 'France', slug: 'fr', currency: 'EUR', symbol: '€', extraPayments: ['Paylib', 'Lydia'] },
    { name: 'Germany', slug: 'de', currency: 'EUR', symbol: '€', extraPayments: ['Giropay', 'SEPA Instant'] },
    { name: 'Ghana', slug: 'gh', currency: 'GHS', symbol: 'GH₵', extraPayments: ['MTN MoMo', 'Telecel Cash'] },
    { name: 'India', slug: 'in', currency: 'INR', symbol: '₹', extraPayments: ['UPI (PhonePe/GPay)', 'Net Banking'] },
    { name: 'Indonesia', slug: 'id', currency: 'IDR', symbol: 'Rp', extraPayments: ['QRIS', 'GoPay', 'OVO'] },
    { name: 'Ireland', slug: 'ie', currency: 'EUR', symbol: '€', extraPayments: ['Revolut Pay'] },
    { name: 'Italy', slug: 'it', currency: 'EUR', symbol: '€', extraPayments: ['Satispay'] },
    { name: 'Japan', slug: 'jp', currency: 'JPY', symbol: '¥', extraPayments: ['PayPay', 'Konbini Cash'] },
    { name: 'Kenya', slug: 'ke', currency: 'KES', symbol: 'KSh', extraPayments: ['M-Pesa', 'Airtel Money'] },
    { name: 'Kuwait', slug: 'kw', currency: 'KWD', symbol: 'د.ك', extraPayments: ['KNET'] },
    { name: 'Malaysia', slug: 'my', currency: 'MYR', symbol: 'RM', extraPayments: ['DuitNow QR', 'Touch \'n Go', 'FPX'] },
    { name: 'Mexico', slug: 'mx', currency: 'MXN', symbol: '$', extraPayments: ['SPEI Transfer', 'OXXO Pay'] },
    { name: 'the Netherlands', slug: 'nl', currency: 'EUR', symbol: '€', extraPayments: ['iDEAL', 'Tikkie'] },
    { name: 'New Zealand', slug: 'nz', currency: 'NZD', symbol: '$', extraPayments: ['POLi Payments'] },
    { name: 'Nigeria', slug: 'ng', currency: 'NGN', symbol: '₦', extraPayments: ['Instant Bank Transfer', 'OPay Wallet'] },
    { name: 'Pakistan', slug: 'pk', currency: 'PKR', symbol: '₨', extraPayments: ['Easypaisa', 'JazzCash'] },
    { name: 'the Philippines', slug: 'ph', currency: 'PHP', symbol: '₱', extraPayments: ['GCash', 'Maya'] },
    { name: 'Poland', slug: 'pl', currency: 'PLN', symbol: 'zł', extraPayments: ['BLIK'] },
    { name: 'Portugal', slug: 'pt', currency: 'EUR', symbol: '€', extraPayments: ['MB Way'] },
    { name: 'Qatar', slug: 'qa', currency: 'QAR', symbol: 'ر.ق', extraPayments: ['QPay'] },
    { name: 'Saudi Arabia', slug: 'sa', currency: 'SAR', symbol: 'ر.س', extraPayments: ['Mada', 'STC Pay'] },
    { name: 'Singapore', slug: 'sg', currency: 'SGD', symbol: '$', extraPayments: ['PayNow'] },
    { name: 'South Africa', slug: 'za', currency: 'ZAR', symbol: 'R', extraPayments: ['PayShap', 'Instant EFT'] },
    { name: 'Spain', slug: 'es', currency: 'EUR', symbol: '€', extraPayments: ['Bizum'] },
    { name: 'Sweden', slug: 'se', currency: 'SEK', symbol: 'kr', extraPayments: ['Swish'] },
    { name: 'Switzerland', slug: 'ch', currency: 'CHF', symbol: 'CHF', extraPayments: ['TWINT'] },
    { name: 'Thailand', slug: 'th', currency: 'THB', symbol: '฿', extraPayments: ['PromptPay', 'TrueMoney'] },
    { name: 'Turkey', slug: 'tr', currency: 'TRY', symbol: '₺', extraPayments: ['FAST Transfer'] },
    { name: 'the United Arab Emirates', slug: 'ae', currency: 'AED', symbol: 'د.إ', extraPayments: ['Jaywan', 'Careem Pay'] },
    { name: 'the United Kingdom', slug: 'uk', currency: 'GBP', symbol: '£', extraPayments: ['Open Banking Transfer'] },
    { name: 'the United States', slug: 'us', currency: 'USD', symbol: '$', extraPayments: ['Venmo', 'Zelle'] },
    { name: 'Vietnam', slug: 'vn', currency: 'VND', symbol: '₫', extraPayments: ['MoMo Wallet', 'ZaloPay', 'VietQR'] }
];